/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/button.vue')['default']
    Card: typeof import('./src/components/card/card.vue')['default']
    Comment: typeof import('./src/components/comment/comment.vue')['default']
    CommentBox: typeof import('./src/components/comment/commentBox.vue')['default']
    CommentList: typeof import('./src/components/comment/commentList.vue')['default']
    CommonHeader: typeof import('./src/components/basic/commonHeader.vue')['default']
    ImgCropper: typeof import('./src/components/utils/imgCropper.vue')['default']
    Input: typeof import('./src/components/form/input/input.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/form/search/search.vue')['default']
  }
}
